version: '3.0'
services:

  app_js:
    build: ./app_server
    container_name: app_js
    ports:
      - "80:80"
    # volumes:
    #   - ./app_server:/app_app
    env_file:
      - db_log.env
      - mail.env
      - pma.env
      - api_token.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - result-tier

  api_js:
    build: ./api_server
    container_name: api_js
    # volumes:
    #   - ./api_server:/app_api
    ports:
      - "8080:8080"
    env_file:
      - db_log.env
      - mail.env
      - pma.env
      - api_token.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - result-tier

  db:
    image: mysql:latest
    restart: always
    container_name: database
    env_file:
      - db_log.env
    ports:
      - "3306"
    volumes:
      - ./data_table.sql:/docker-entrypoint-initdb.d/setup.sql
      - db-data:/var/lib/mysql
    networks:
      - result-tier
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 1s
      retries: 30

  phpmyadmin:
    image: phpmyadmin
    container_name: PHPmyAdmin
    networks:
      - result-tier
    env_file:
      - pma.env
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db

networks:
  result-tier:

volumes:
  db-data:
    driver: local

